-- Native PostgreSQL board storage. Provision offline as the NOLOGIN owner.

CREATE TABLE board_registry (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    state TEXT NOT NULL DEFAULT 'live' CHECK (state IN ('live','deleted'))
);
CREATE TABLE board_fs_operations (
    id TEXT PRIMARY KEY,
    board_id TEXT NOT NULL REFERENCES board_registry(id),
    source_name TEXT NOT NULL,
    target_name TEXT NOT NULL,
    kind TEXT NOT NULL CHECK (kind IN ('archive','delete'))
);

CREATE TABLE tasks (
    board_id TEXT NOT NULL DEFAULT current_setting('buildstudio.kanban_board'),
    id                   TEXT NOT NULL,
    title                TEXT NOT NULL,
    body                 TEXT,
    assignee             TEXT,
    status               TEXT NOT NULL,
    priority             BIGINT DEFAULT 0,
    created_by           TEXT,
    created_at           BIGINT NOT NULL,
    started_at           BIGINT,
    completed_at         BIGINT,
    workspace_kind       TEXT NOT NULL DEFAULT 'scratch',
    workspace_path       TEXT,
    branch_name          TEXT,

    project_id           TEXT,
    claim_lock           TEXT,
    claim_expires        BIGINT,
    tenant               TEXT,
    result               TEXT,
    idempotency_key      TEXT,

    consecutive_failures BIGINT NOT NULL DEFAULT 0,
    worker_pid           BIGINT,

    last_failure_error   TEXT,
    max_runtime_seconds  BIGINT,
    last_heartbeat_at    BIGINT,

    current_run_id       BIGINT,

    workflow_template_id TEXT,
    current_step_key     TEXT,

    skills               TEXT,

    model_override       TEXT,

    provider_override    TEXT,

    reasoning_effort     TEXT,

    max_retries          BIGINT,

    goal_mode            BIGINT NOT NULL DEFAULT 0,

    goal_max_turns       BIGINT,

    session_id           TEXT,

    block_kind           TEXT,

    block_recurrences    BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (board_id,id)
);

CREATE TABLE task_links (
    board_id TEXT NOT NULL DEFAULT current_setting('buildstudio.kanban_board'),
    parent_id  TEXT NOT NULL,
    child_id   TEXT NOT NULL,
    PRIMARY KEY (board_id, parent_id, child_id)
);

CREATE TABLE task_comments (
    board_id TEXT NOT NULL DEFAULT current_setting('buildstudio.kanban_board'),
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    task_id    TEXT NOT NULL,
    author     TEXT NOT NULL,
    body       TEXT NOT NULL,
    created_at BIGINT NOT NULL,
    PRIMARY KEY (board_id,id)
);

CREATE TABLE task_events (
    board_id TEXT NOT NULL DEFAULT current_setting('buildstudio.kanban_board'),
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    task_id    TEXT NOT NULL,
    run_id     BIGINT,
    kind       TEXT NOT NULL,
    payload    TEXT,
    created_at BIGINT NOT NULL,
    PRIMARY KEY (board_id,id)
);

CREATE TABLE task_runs (
    board_id TEXT NOT NULL DEFAULT current_setting('buildstudio.kanban_board'),
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    task_id             TEXT NOT NULL,
    profile             TEXT,
    step_key            TEXT,
    status              TEXT NOT NULL,

    claim_lock          TEXT,
    claim_expires       BIGINT,
    worker_pid          BIGINT,
    max_runtime_seconds BIGINT,
    last_heartbeat_at   BIGINT,
    started_at          BIGINT NOT NULL,
    ended_at            BIGINT,
    outcome             TEXT,

    summary             TEXT,
    metadata            TEXT,
    error               TEXT,
    PRIMARY KEY (board_id,id)
);

CREATE TABLE task_attachments (
    board_id TEXT NOT NULL DEFAULT current_setting('buildstudio.kanban_board'),
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    task_id      TEXT NOT NULL,
    filename     TEXT NOT NULL,
    stored_path  TEXT NOT NULL,
    content_type TEXT,
    size         BIGINT NOT NULL DEFAULT 0,
    uploaded_by  TEXT,
    created_at   BIGINT NOT NULL,
    PRIMARY KEY (board_id,id)
);

CREATE TABLE kanban_notify_subs (
    board_id TEXT NOT NULL DEFAULT current_setting('buildstudio.kanban_board'),
    task_id       TEXT NOT NULL,
    platform      TEXT NOT NULL,
    chat_id       TEXT NOT NULL,
    thread_id     TEXT NOT NULL DEFAULT '',
    user_id       TEXT,
    user_id_alt   TEXT,
    chat_type     TEXT,
    notifier_profile TEXT,
    delivery_mode TEXT NOT NULL DEFAULT 'notify',
    delivery_metadata TEXT,
    created_at    BIGINT NOT NULL,
    last_event_id BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (board_id, task_id, platform, chat_id, thread_id)
);

CREATE INDEX IF NOT EXISTS idx_tasks_assignee_status ON tasks(board_id,assignee, status);
CREATE INDEX IF NOT EXISTS idx_tasks_status          ON tasks(board_id,status);
CREATE INDEX IF NOT EXISTS idx_links_child           ON task_links(board_id,child_id);
CREATE INDEX IF NOT EXISTS idx_links_parent          ON task_links(board_id,parent_id);
CREATE INDEX IF NOT EXISTS idx_comments_task         ON task_comments(board_id,task_id, created_at);
CREATE INDEX IF NOT EXISTS idx_events_task           ON task_events(board_id,task_id, created_at);
CREATE INDEX IF NOT EXISTS idx_runs_task             ON task_runs(board_id,task_id, started_at);
CREATE INDEX IF NOT EXISTS idx_runs_status           ON task_runs(board_id,status);
CREATE INDEX IF NOT EXISTS idx_attachments_task      ON task_attachments(board_id,task_id, created_at);
CREATE INDEX IF NOT EXISTS idx_notify_task           ON kanban_notify_subs(board_id,task_id);

ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks FORCE ROW LEVEL SECURITY;
CREATE POLICY board_scope ON tasks USING (board_id = current_setting('buildstudio.kanban_board') AND EXISTS (SELECT 1 FROM board_registry b WHERE b.id = board_id AND b.state = 'live')) WITH CHECK (board_id = current_setting('buildstudio.kanban_board') AND EXISTS (SELECT 1 FROM board_registry b WHERE b.id = board_id AND b.state = 'live'));

ALTER TABLE task_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_links FORCE ROW LEVEL SECURITY;
CREATE POLICY board_scope ON task_links USING (board_id = current_setting('buildstudio.kanban_board') AND EXISTS (SELECT 1 FROM board_registry b WHERE b.id = board_id AND b.state = 'live')) WITH CHECK (board_id = current_setting('buildstudio.kanban_board') AND EXISTS (SELECT 1 FROM board_registry b WHERE b.id = board_id AND b.state = 'live'));

ALTER TABLE task_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_comments FORCE ROW LEVEL SECURITY;
CREATE POLICY board_scope ON task_comments USING (board_id = current_setting('buildstudio.kanban_board') AND EXISTS (SELECT 1 FROM board_registry b WHERE b.id = board_id AND b.state = 'live')) WITH CHECK (board_id = current_setting('buildstudio.kanban_board') AND EXISTS (SELECT 1 FROM board_registry b WHERE b.id = board_id AND b.state = 'live'));

ALTER TABLE task_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_events FORCE ROW LEVEL SECURITY;
CREATE POLICY board_scope ON task_events USING (board_id = current_setting('buildstudio.kanban_board') AND EXISTS (SELECT 1 FROM board_registry b WHERE b.id = board_id AND b.state = 'live')) WITH CHECK (board_id = current_setting('buildstudio.kanban_board') AND EXISTS (SELECT 1 FROM board_registry b WHERE b.id = board_id AND b.state = 'live'));

ALTER TABLE task_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_runs FORCE ROW LEVEL SECURITY;
CREATE POLICY board_scope ON task_runs USING (board_id = current_setting('buildstudio.kanban_board') AND EXISTS (SELECT 1 FROM board_registry b WHERE b.id = board_id AND b.state = 'live')) WITH CHECK (board_id = current_setting('buildstudio.kanban_board') AND EXISTS (SELECT 1 FROM board_registry b WHERE b.id = board_id AND b.state = 'live'));

ALTER TABLE task_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_attachments FORCE ROW LEVEL SECURITY;
CREATE POLICY board_scope ON task_attachments USING (board_id = current_setting('buildstudio.kanban_board') AND EXISTS (SELECT 1 FROM board_registry b WHERE b.id = board_id AND b.state = 'live')) WITH CHECK (board_id = current_setting('buildstudio.kanban_board') AND EXISTS (SELECT 1 FROM board_registry b WHERE b.id = board_id AND b.state = 'live'));

ALTER TABLE kanban_notify_subs ENABLE ROW LEVEL SECURITY;
ALTER TABLE kanban_notify_subs FORCE ROW LEVEL SECURITY;
CREATE POLICY board_scope ON kanban_notify_subs USING (board_id = current_setting('buildstudio.kanban_board') AND EXISTS (SELECT 1 FROM board_registry b WHERE b.id = board_id AND b.state = 'live')) WITH CHECK (board_id = current_setting('buildstudio.kanban_board') AND EXISTS (SELECT 1 FROM board_registry b WHERE b.id = board_id AND b.state = 'live'));

CREATE INDEX idx_tasks_session_id ON tasks(board_id,session_id);
CREATE INDEX idx_tasks_tenant ON tasks(board_id,tenant);
CREATE INDEX idx_tasks_idempotency ON tasks(board_id,idempotency_key);
CREATE INDEX idx_events_run ON task_events(board_id,run_id,id);
