"""Offline DDL and transactional, lossless import for operational Agent stores.

Run only after stopping all writers. Runtime roles must not have CREATE or
sequence UPDATE privileges. The caller supplies a temporary migration role;
credentials and source rows are never written to an ordinary report.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
import re
import sqlite3

from hermes_cli.postgres_runtime import SCOPES

SCHEMA_SQL = {
    "responses": """
        CREATE TABLE responses(response_id text PRIMARY KEY, data text NOT NULL,
                               accessed_at double precision NOT NULL);
        CREATE TABLE conversations(name text PRIMARY KEY, response_id text NOT NULL);
    """,
    "runs": """
        CREATE TABLE run_idempotency (
            scope text NOT NULL, idempotency_key text NOT NULL,
            fingerprint text NOT NULL, run_id text NOT NULL UNIQUE,
            status_json text NOT NULL, owner_pid bigint NOT NULL DEFAULT 0,
            owner_started bigint NOT NULL DEFAULT 0,
            retention_until double precision NOT NULL DEFAULT 0,
            acknowledged_at double precision, created_at double precision NOT NULL,
            updated_at double precision NOT NULL, PRIMARY KEY(scope,idempotency_key)
        );
    """,
    "artifacts": """
        CREATE TABLE chat_file_artifacts (
            artifact_id text PRIMARY KEY, owner_id text NOT NULL,
            chat_id text NOT NULL DEFAULT '', path text NOT NULL, filename text NOT NULL,
            content_type text NOT NULL, size_bytes bigint NOT NULL, mtime_ns bigint NOT NULL,
            expires_at double precision NOT NULL
        );
        CREATE INDEX chat_file_artifacts_source ON chat_file_artifacts
            (owner_id,chat_id,path,size_bytes,mtime_ns,expires_at);
    """,
    "verification": """
        CREATE TABLE meta(key text PRIMARY KEY,value text NOT NULL);
        CREATE TABLE verification_events (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at text NOT NULL,
            session_id text NOT NULL,cwd text NOT NULL,root text NOT NULL,
            command text NOT NULL,canonical_command text NOT NULL,kind text NOT NULL,
            scope text NOT NULL,status text NOT NULL,exit_code bigint NOT NULL,
            output_summary text NOT NULL
        );
        CREATE TABLE verification_state (
            session_id text NOT NULL,root text NOT NULL,last_event_id bigint,
            last_edit_at text,changed_paths_json text NOT NULL DEFAULT '[]',
            PRIMARY KEY(session_id,root)
        );
        CREATE INDEX idx_verification_events_session_root
            ON verification_events(session_id,root,id DESC);
    """,
}


def _digest(rows):
    digest = hashlib.sha256()
    for row in rows:
        digest.update(json.dumps(list(row), ensure_ascii=False, separators=(",", ":"),
                                 allow_nan=False).encode("utf-8") + b"\n")
    return digest.hexdigest()


def import_stores(source_home: Path, settings: dict, scopes=None):
    """Import all selected stores in ONE PostgreSQL transaction, or import none."""
    import psycopg
    from psycopg import sql

    scopes = list(scopes if scopes is not None else SCOPES)
    if not scopes or set(scopes) - SCOPES.keys() or len(scopes) != len(set(scopes)):
        raise ValueError("Invalid migration scopes")
    for scope in scopes:
        if not re.fullmatch(r"agent_[a-z0-9_]{1,48}", settings["schemas"][scope]):
            raise ValueError("Invalid migration schema")
    sources = {}
    try:
        for scope in scopes:
            path = (Path(source_home) / SCOPES[scope][0]).resolve(strict=True)
            old = sqlite3.connect(path.as_uri() + "?mode=ro", uri=True)
            sources[scope] = old
            old.execute("BEGIN")
            if old.execute("PRAGMA quick_check").fetchall() != [("ok",)]:
                raise RuntimeError("Source integrity check failed: " + scope)
            actual = {row[0] for row in old.execute(
                "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'")}
            if actual != set(SCOPES[scope][1]):
                raise RuntimeError("Unexpected source tables: " + scope)
        receipt = {}
        with psycopg.connect(**settings["connection"]) as db:
            owner = settings.get("owner_role")
            if owner is not None:
                if owner != "there_agent_operational_owner":
                    raise ValueError("Unexpected offline migration owner")
                db.execute(sql.SQL("SET LOCAL ROLE {}").format(sql.Identifier(owner)))
            db.execute("SET LOCAL lock_timeout='5s'")
            db.execute("SET LOCAL statement_timeout='60s'")
            for scope in scopes:
                schema = settings["schemas"][scope]
                old = sources[scope]
                for table in SCOPES[scope][1]:
                    info = old.execute(f'PRAGMA table_info("{table}")').fetchall()
                    columns = [row[1] for row in info]
                    primary = [row[1] for row in sorted(info, key=lambda row: row[5]) if row[5]]
                    if not primary:
                        raise RuntimeError("Migration requires a stable primary key")
                    target = sql.SQL("{}.{}").format(sql.Identifier(schema), sql.Identifier(table))
                    db.execute(sql.SQL("LOCK TABLE {} IN ACCESS EXCLUSIVE MODE").format(target))
                    target_columns = {row[0] for row in db.execute(
                        "SELECT column_name FROM information_schema.columns WHERE table_schema=%s AND table_name=%s",
                        (schema, table))}
                    if target_columns != set(columns):
                        raise RuntimeError("Unexpected columns: " + scope + "." + table)
                    if db.execute(sql.SQL("SELECT count(*) FROM {}").format(target)).fetchone()[0]:
                        raise RuntimeError("Target is not empty: " + scope + "." + table)
                    # Names are an exact allowlisted table and introspected columns;
                    # quote identifiers instead of interpolating source contents.
                    quoted = lambda name: '"' + name.replace('"', '""') + '"'
                    rows = old.execute('SELECT ' + ','.join(map(quoted, columns)) +
                        ' FROM ' + quoted(table) + ' ORDER BY ' + ','.join(map(quoted, primary))).fetchall()
                    with db.cursor() as cursor:
                        cursor.executemany(sql.SQL("INSERT INTO {} ({}) VALUES ({})").format(
                            target, sql.SQL(",").join(map(sql.Identifier, columns)),
                            sql.SQL(",").join(sql.Placeholder() for _ in columns)), rows)
                    actual = db.execute(sql.SQL("SELECT {} FROM {} ORDER BY {}").format(
                        sql.SQL(",").join(map(sql.Identifier, columns)), target,
                        sql.SQL(",").join(map(sql.Identifier, primary)))).fetchall()
                    # Cross-engine text collations can order keys differently.
                    # Hash a canonical JSON sort, independent of server locale.
                    canonical = lambda values: sorted(values, key=lambda row: json.dumps(list(row), ensure_ascii=False))
                    if len(actual) != len(rows) or _digest(canonical(actual)) != _digest(canonical(rows)):
                        raise RuntimeError("Content verification failed: " + scope + "." + table)
                    receipt[scope + "." + table] = {"rows": len(rows), "sha256": _digest(canonical(actual))}
                if scope == "verification":
                    table = sql.SQL("{}.verification_events").format(sql.Identifier(schema))
                    maximum = db.execute(sql.SQL("SELECT max(id) FROM {}").format(table)).fetchone()[0]
                    # ALTER IDENTITY is transactional, unlike setval(): a later
                    # failure must also roll back the imported sequence position.
                    db.execute(sql.SQL("ALTER TABLE {} ALTER COLUMN id RESTART WITH {}").format(
                        table, sql.Literal(maximum + 1 if maximum is not None else 1)))
            return receipt
    finally:
        for old in sources.values():
            old.close()
