-- Native SessionDB schema, revision 1. Applied OFFLINE by the migration owner.
-- Mirrors canonical schema version 26 plus supported gateway stores.
-- No SQLite virtual tables or copied search indexes. No runtime DDL rights.

CREATE TABLE schema_version (
    version BIGINT NOT NULL
);

CREATE TABLE system_prompts (
    hash TEXT PRIMARY KEY,
    prompt TEXT NOT NULL
);

CREATE TABLE sessions (
    id TEXT PRIMARY KEY,
    source TEXT NOT NULL,
    user_id TEXT,
    session_key TEXT,
    chat_id TEXT,
    chat_type TEXT,
    thread_id TEXT,
    display_name TEXT,
    origin_json TEXT,
    expiry_finalized BIGINT DEFAULT 0,
    model TEXT,
    model_config TEXT,
    system_prompt TEXT,
    system_prompt_hash TEXT,
    parent_session_id TEXT,
    started_at DOUBLE PRECISION NOT NULL,
    ended_at DOUBLE PRECISION,
    end_reason TEXT,
    message_count BIGINT DEFAULT 0,
    tool_call_count BIGINT DEFAULT 0,
    input_tokens BIGINT DEFAULT 0,
    output_tokens BIGINT DEFAULT 0,
    cache_read_tokens BIGINT DEFAULT 0,
    cache_write_tokens BIGINT DEFAULT 0,
    reasoning_tokens BIGINT DEFAULT 0,
    cwd TEXT,
    git_branch TEXT,
    git_repo_root TEXT,
    git_metadata_generation BIGINT NOT NULL DEFAULT 0,
    billing_provider TEXT,
    billing_base_url TEXT,
    billing_mode TEXT,
    estimated_cost_usd DOUBLE PRECISION,
    actual_cost_usd DOUBLE PRECISION,
    cost_status TEXT,
    cost_source TEXT,
    pricing_version TEXT,
    title TEXT,
    title_source TEXT,
    last_activity_at DOUBLE PRECISION,
    last_activity_description TEXT,
    last_activity_provenance TEXT,
    api_call_count BIGINT DEFAULT 0,
    handoff_state TEXT,
    handoff_platform TEXT,
    handoff_error TEXT,
    compression_failure_cooldown_until DOUBLE PRECISION,
    compression_failure_error TEXT,
    compression_fallback_streak BIGINT NOT NULL DEFAULT 0,
    compression_ineffective_count BIGINT NOT NULL DEFAULT 0,
    profile_name TEXT,
    rewind_count BIGINT NOT NULL DEFAULT 0,
    archived BIGINT NOT NULL DEFAULT 0,
    pinned BIGINT NOT NULL DEFAULT 0,
    hidden BIGINT NOT NULL DEFAULT 0,
    last_read_at DOUBLE PRECISION,
    FOREIGN KEY (parent_session_id) REFERENCES sessions(id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (system_prompt_hash) REFERENCES system_prompts(hash) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(id) DEFERRABLE INITIALLY DEFERRED,
    role TEXT NOT NULL,
    content TEXT,
    tool_call_id TEXT,
    tool_calls TEXT,
    tool_name TEXT,
    effect_disposition TEXT,
    timestamp DOUBLE PRECISION NOT NULL,
    token_count BIGINT,
    finish_reason TEXT,
    reasoning TEXT,
    reasoning_content TEXT,
    reasoning_details TEXT,
    codex_reasoning_items TEXT,
    codex_message_items TEXT,
    platform_message_id TEXT,
    observed BIGINT DEFAULT 0,
    _compressed_summary BIGINT NOT NULL DEFAULT 0,
    active BIGINT NOT NULL DEFAULT 1,
    compacted BIGINT NOT NULL DEFAULT 0,
    api_content TEXT,
    display_kind TEXT,
    display_metadata TEXT
);

CREATE TABLE session_model_usage (
    session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    model TEXT NOT NULL,
    billing_provider TEXT NOT NULL DEFAULT '',
    billing_base_url TEXT NOT NULL DEFAULT '',
    billing_mode TEXT NOT NULL DEFAULT '',
    task TEXT NOT NULL DEFAULT '',
    api_call_count BIGINT NOT NULL DEFAULT 0,
    input_tokens BIGINT NOT NULL DEFAULT 0,
    output_tokens BIGINT NOT NULL DEFAULT 0,
    cache_read_tokens BIGINT NOT NULL DEFAULT 0,
    cache_write_tokens BIGINT NOT NULL DEFAULT 0,
    reasoning_tokens BIGINT NOT NULL DEFAULT 0,
    estimated_cost_usd DOUBLE PRECISION NOT NULL DEFAULT 0,
    actual_cost_usd DOUBLE PRECISION NOT NULL DEFAULT 0,
    cost_status TEXT,
    cost_source TEXT,
    first_seen DOUBLE PRECISION,
    last_seen DOUBLE PRECISION,
    PRIMARY KEY (session_id, model, billing_provider, billing_base_url, billing_mode, task)
);

CREATE TABLE state_meta (
    key TEXT PRIMARY KEY,
    value TEXT
);

CREATE TABLE gateway_routing (
    scope TEXT NOT NULL DEFAULT '',
    session_key TEXT NOT NULL,
    entry_json TEXT NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (scope, session_key)
);

CREATE TABLE gateway_hygiene_state (
    session_key TEXT PRIMARY KEY,
    failure_streak BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE gateway_heartbeats (
    backend_id TEXT PRIMARY KEY,
    pid BIGINT NOT NULL,
    started_at DOUBLE PRECISION NOT NULL,
    last_heartbeat DOUBLE PRECISION NOT NULL,
    profile TEXT NOT NULL DEFAULT '',
    host TEXT NOT NULL DEFAULT ''
);

CREATE TABLE compression_locks (
    session_id TEXT PRIMARY KEY,
    holder TEXT NOT NULL,
    acquired_at DOUBLE PRECISION NOT NULL,
    expires_at DOUBLE PRECISION NOT NULL
);

CREATE TABLE session_turn_leases (
    conversation_id TEXT PRIMARY KEY,
    holder TEXT NOT NULL,
    acquired_at DOUBLE PRECISION NOT NULL,
    expires_at DOUBLE PRECISION NOT NULL
);

CREATE TABLE async_delegations (
    delegation_id TEXT PRIMARY KEY,
    origin_session TEXT NOT NULL,
    origin_ui_session_id TEXT NOT NULL DEFAULT '',
    parent_session_id TEXT,
    state TEXT NOT NULL,
    dispatched_at DOUBLE PRECISION NOT NULL,
    completed_at DOUBLE PRECISION,
    updated_at DOUBLE PRECISION NOT NULL,
    event_json TEXT,
    result_json TEXT,
    delivery_state TEXT NOT NULL DEFAULT 'pending',
    delivery_attempts BIGINT NOT NULL DEFAULT 0,
    delivered_at DOUBLE PRECISION,
    owner_pid BIGINT,
    owner_started_at BIGINT,
    task_json TEXT,
    delivery_claim TEXT,
    delivery_claimed_at DOUBLE PRECISION,
    -- Added by tools.async_delegation even when SessionDB v26 is already current.
    -- Older lazy migrations allow NULL; preserve those values.
    origin_session_id TEXT DEFAULT ''
);

CREATE TABLE telegram_dm_topic_mode (
    chat_id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    enabled BIGINT NOT NULL DEFAULT 1,
    activated_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL,
    has_topics_enabled BIGINT,
    allows_users_to_create_topics BIGINT,
    capability_checked_at DOUBLE PRECISION,
    intro_message_id TEXT,
    pinned_message_id TEXT
);

CREATE TABLE telegram_dm_topic_bindings (
    chat_id TEXT NOT NULL,
    thread_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    session_key TEXT NOT NULL,
    session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    managed_mode TEXT NOT NULL DEFAULT 'auto',
    linked_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (chat_id, thread_id)
);

CREATE TABLE hosted_rooms (
    room_id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    members_json TEXT NOT NULL,
    authority_gateway_id TEXT NOT NULL,
    authority_epoch BIGINT NOT NULL DEFAULT 1 CHECK (authority_epoch >= 1),
    next_seq BIGINT NOT NULL DEFAULT 1 CHECK (next_seq >= 1),
    event_bytes BIGINT NOT NULL DEFAULT 0 CHECK (event_bytes >= 0),
    revision BIGINT NOT NULL DEFAULT 1 CHECK (revision >= 1),
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL,
    disbanded_at DOUBLE PRECISION
);

CREATE TABLE hosted_room_events (
    room_id TEXT NOT NULL,
    seq BIGINT NOT NULL CHECK (seq >= 1),
    event_id TEXT NOT NULL,
    kind TEXT NOT NULL,
    actor_json TEXT NOT NULL,
    authority_epoch BIGINT CHECK (authority_epoch IS NULL OR authority_epoch >= 1),
    payload_json TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (room_id, seq),
    UNIQUE (room_id, event_id),
    FOREIGN KEY (room_id) REFERENCES hosted_rooms(room_id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE hosted_room_retired_ids (
    room_id TEXT PRIMARY KEY,
    retired_at DOUBLE PRECISION NOT NULL
);

CREATE TABLE hosted_room_links (
    room_id TEXT NOT NULL,
    member_id TEXT NOT NULL,
    target_url TEXT NOT NULL,
    target_profile TEXT NOT NULL,
    "grant" TEXT NOT NULL,
    catalog_json TEXT NOT NULL,
    cancellation_scope_id TEXT NOT NULL,
    trace_id TEXT NOT NULL,
    transport_security TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'ready',
    updated_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (room_id, member_id)
);

CREATE TABLE hosted_room_remote_runs (
    room_id TEXT NOT NULL,
    home_install_id TEXT NOT NULL,
    authority_gateway_id TEXT NOT NULL,
    authority_epoch BIGINT NOT NULL CHECK (authority_epoch >= 1),
    member_id TEXT NOT NULL,
    task_id TEXT NOT NULL,
    execution_generation BIGINT NOT NULL CHECK (execution_generation >= 1),
    target_install_id TEXT NOT NULL,
    target_profile TEXT NOT NULL,
    run_id TEXT NOT NULL,
    session_id TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (
        room_id, home_install_id, authority_gateway_id, authority_epoch,
        member_id, target_install_id, target_profile, task_id,
        execution_generation
    )
);

CREATE TABLE hosted_room_revoked_grants (
    scope_key TEXT PRIMARY KEY,
    expires_at DOUBLE PRECISION NOT NULL,
    revoked_before DOUBLE PRECISION NOT NULL
);

CREATE TABLE hosted_room_peer_reservations (
    room_id TEXT NOT NULL,
    member_id TEXT NOT NULL,
    target_profile TEXT NOT NULL,
    authority_gateway_id TEXT NOT NULL,
    authority_epoch BIGINT NOT NULL CHECK (authority_epoch >= 1),
    expires_at DOUBLE PRECISION NOT NULL,
    revoked_at DOUBLE PRECISION,
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (room_id, member_id, target_profile)
);

CREATE TABLE hosted_room_policy_cursors (
    room_id TEXT PRIMARY KEY,
    through_seq BIGINT NOT NULL DEFAULT 0,
    stopped_through_seq BIGINT NOT NULL DEFAULT 0,
    updated_at DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE TABLE hosted_room_policy_threads (
    room_id TEXT NOT NULL,
    thread_id TEXT NOT NULL,
    discussion_event_id TEXT NOT NULL,
    latest_user_seq BIGINT NOT NULL,
    completed BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY(room_id, thread_id)
);

CREATE TABLE hosted_room_policy_events (
    room_id TEXT NOT NULL,
    thread_id TEXT NOT NULL,
    discussion_event_id TEXT NOT NULL,
    seq BIGINT NOT NULL,
    event_json TEXT NOT NULL,
    PRIMARY KEY(room_id, seq)
);

CREATE TABLE hosted_room_policy_watermarks (
    room_id TEXT NOT NULL,
    thread_id TEXT NOT NULL,
    member_id TEXT NOT NULL,
    seen_through_seq BIGINT NOT NULL,
    PRIMARY KEY(room_id, thread_id, member_id)
);

CREATE TABLE hosted_room_policy_publications (
    room_id TEXT NOT NULL,
    task_id TEXT NOT NULL,
    kind TEXT NOT NULL,
    execution_generation BIGINT NOT NULL DEFAULT 0,
    seq BIGINT NOT NULL,
    PRIMARY KEY(room_id, task_id, kind, execution_generation)
);

CREATE TABLE hosted_room_policy_transcript (
    room_id TEXT NOT NULL,
    thread_id TEXT NOT NULL,
    seq BIGINT NOT NULL,
    kind TEXT NOT NULL,
    settled_seq BIGINT,
    PRIMARY KEY(room_id, thread_id, seq)
);

CREATE TABLE hosted_room_policy_transcript_state (
    room_id TEXT PRIMARY KEY,
    schema_version BIGINT NOT NULL
);

CREATE TABLE hosted_room_driver_leases (
    room_id TEXT PRIMARY KEY,
    gateway_id TEXT NOT NULL,
    authority_epoch BIGINT NOT NULL CHECK (authority_epoch >= 1),
    process_generation TEXT NOT NULL,
    lease_generation BIGINT NOT NULL CHECK (lease_generation >= 1),
    expires_at DOUBLE PRECISION NOT NULL,
    acquired_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL,
    released_at DOUBLE PRECISION,
    FOREIGN KEY (room_id) REFERENCES hosted_rooms(room_id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE hosted_room_driver_tasks (
    room_id TEXT NOT NULL,
    task_id TEXT NOT NULL,
    thread_id TEXT NOT NULL,
    turn_id TEXT NOT NULL,
    source_event_seq BIGINT NOT NULL CHECK (source_event_seq >= 1),
    payload_json TEXT NOT NULL,
    payload_digest TEXT NOT NULL,
    status TEXT NOT NULL CHECK (
        status IN (
            'queued', 'running', 'settled', 'failed',
            'cancelled', 'indeterminate', 'deferred', 'stopping'
        )
    ),
    execution_generation BIGINT NOT NULL DEFAULT 0
        CHECK (execution_generation >= 0),
    cancel_generation BIGINT NOT NULL DEFAULT 0
        CHECK (cancel_generation >= 0),
    run_gateway_id TEXT,
    run_process_generation TEXT,
    run_lease_generation BIGINT,
    cancel_id TEXT,
    settlement_id TEXT,
    settlement_status TEXT,
    result_json TEXT,
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL,
    started_at DOUBLE PRECISION,
    terminal_at DOUBLE PRECISION,
    indeterminate_at DOUBLE PRECISION,
    PRIMARY KEY (room_id, task_id),
    UNIQUE (room_id, thread_id, turn_id),
    FOREIGN KEY (room_id) REFERENCES hosted_rooms(room_id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE delivery_obligations (
    obligation_id TEXT PRIMARY KEY,
    session_key TEXT NOT NULL,
    platform TEXT NOT NULL,
    chat_id TEXT NOT NULL,
    thread_id TEXT,
    content TEXT NOT NULL,
    state TEXT NOT NULL,
    attempts BIGINT NOT NULL DEFAULT 0,
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL,
    owner_pid BIGINT,
    owner_started_at BIGINT,
    last_error TEXT,
    adapter_profile TEXT
);

CREATE INDEX idx_sessions_source ON sessions(source);

CREATE INDEX idx_sessions_source_id ON sessions(source, id);

CREATE INDEX idx_sessions_parent ON sessions(parent_session_id);

CREATE INDEX idx_sessions_started ON sessions(started_at DESC);

CREATE INDEX idx_messages_session ON messages(session_id, timestamp);

CREATE INDEX idx_messages_session_id ON messages(session_id, id);

CREATE INDEX idx_messages_assistant_calls_by_session
    ON messages(session_id)
    WHERE role = 'assistant' AND tool_calls IS NOT NULL;

CREATE INDEX idx_compression_locks_expires ON compression_locks(expires_at);

CREATE INDEX idx_session_turn_leases_expires ON session_turn_leases(expires_at);

CREATE INDEX idx_session_model_usage_session ON session_model_usage(session_id);

CREATE INDEX idx_session_model_usage_model ON session_model_usage(model);

CREATE INDEX idx_async_delegations_delivery
    ON async_delegations(delivery_state, completed_at);

CREATE INDEX idx_messages_platform_msg_id ON messages(session_id, platform_message_id) WHERE platform_message_id IS NOT NULL;

CREATE INDEX idx_messages_session_active
    ON messages(session_id, active, timestamp);

CREATE INDEX idx_messages_active_null
    ON messages(active) WHERE active IS NULL;

CREATE INDEX idx_sessions_session_key
    ON sessions(session_key, started_at DESC);

CREATE INDEX idx_sessions_gateway_peer
    ON sessions(source, user_id, chat_id, chat_type, thread_id, started_at DESC);

CREATE INDEX idx_sessions_handoff_state
    ON sessions(handoff_state, started_at);

CREATE INDEX idx_sessions_system_prompt_hash
    ON sessions(system_prompt_hash);

CREATE UNIQUE INDEX idx_sessions_title_unique ON sessions(title) WHERE title IS NOT NULL;

CREATE UNIQUE INDEX idx_telegram_dm_topic_bindings_session
                ON telegram_dm_topic_bindings(session_id);

CREATE INDEX idx_telegram_dm_topic_bindings_user
                ON telegram_dm_topic_bindings(user_id, chat_id);

CREATE INDEX idx_hosted_room_events_cursor
           ON hosted_room_events(room_id, seq);

CREATE INDEX idx_hosted_room_policy_pending
                   ON hosted_room_policy_threads(
                       room_id, completed, latest_user_seq, thread_id
                   );

CREATE INDEX idx_hosted_room_policy_events_active
                   ON hosted_room_policy_events(
                       room_id, discussion_event_id, seq
                   );

CREATE INDEX idx_hosted_room_driver_tasks_status
           ON hosted_room_driver_tasks(
               room_id, status, source_event_seq, created_at, task_id
           );
